<center> <img src="logo_ifba.jpg" alt="jpg_python" width="100" height="200"> </center>
<br><br>
<div align="center"><span style="font-size: 26px;"><strong>Cálculo Numérico <br></strong></span></div> <br>
<center> <img src="python_gif.gif" alt="gif_python" width="80"> </center>


<div style="border: 2px solid black; padding: 10px; width: 95%; background-color: lightgray; display: flex; align-items: center;">
    <h1 style="color: red; text-align: center; margin: auto;">
        Capítulo 17: Método Direto da Decomposição LU
    </h1>
</div>

<font color='red'></font>
<a href=""></a>

# <div style="margin-top: -20px;">
<hr style="border: 2px solid black;">

<font color='black'><span style="font-size: 22px;"><strong>17.1 Decomposição LU</strong></span></font>

<hr style="border: 2px solid black;">
</div>

A decomposição $LU$ é uma forma de fatoração de uma matriz não singular como o produto de uma matriz triangular inferior (lower) e uma matriz triangular superior (upper), isto é:<br><br>
$$
A = LU \Leftrightarrow \left[ \begin{array}{cccc}
a_{11} & a_{12} & \ldots & a_{1n} \\
a_{21} & a_{22} & \ldots & a_{2n} \\
\vdots & \vdots & \ldots & \vdots \\
a_{n1} & a_{n2} & \ldots & a_{nn} \\
\end{array}\right]
=
\left[ \begin{array}{cccc}
1 		& 0 	  & \ldots & 0 \\
-m_{21} & 1 	  & \ldots & 0 \\
\vdots & \vdots 	  & \ldots & \vdots \\
-m_{n1} & -m_{n2} & \ldots& 1 \\
\end{array}\right]
\cdot
\left[ \begin{array}{cccc}
u_{11} 	& u_{12} & \ldots & u_{13} \\
0 		& u_{22} & & u_{23} \\
\vdots 		& \vdots & \ldots & \vdots \\
0	 	& 0		 & \ldots & u_{nn} \\
\end{array}\right]
$$<br>
É possível mostrar que os valores $m_{ij}$ são os fatores multiplicativos resultantes do escalonamento da matriz $A$ e os valores $u_{ij}$ são advindos da matriz triangular superior resultante. Em particular, para matrizes $3 \times 3$, temos:<br><br>
$$
\left[ \begin{array}{ccc}
a_{11} & a_{12} & a_{13} \\
a_{21} & a_{22} & a_{23} \\
a_{31} & a_{32} & a_{33} \\
\end{array}\right]
=
\left[ \begin{array}{ccc}
1 		& 0 	  & 0 \\
-m_{21} & 1 	  & 0 \\
-m_{31} & -m_{32} & 1 \\
\end{array}\right]
\cdot
\left[ \begin{array}{ccc}
u_{11} 	& u_{12} & u_{13} \\
0 		& u_{22} & u_{23} \\
0	 	& 0		 & u_{33} \\
\end{array}\right]
$$

#### <font color='red'> Teorema 1 </font>

<font color='red'> Seja $A_{n \times n}$ uma matriz qualquer e $A_{kk}$ uma submatriz de $A_{n \times n}$ formada pela intersecção das primeiras $k$ linha e $k$ colunas. Se $det(A) \neq 0$ para $k = 1, \ldots, n-1$, então existem e são \'unicasas matrizes $L$ e $U$.

#### <font color='blue'> Exemplo 1 </font>

<font color='blue'> Obtenha as matrizes $L$ e $U$ associadas a matriz<br><br>
 $$
A = \left[ \begin{array}{ccc}
1 & 3 & 2 \\
2 & 1 & -1 \\
1 & 0 & 1 \\
\end{array}\right].
$$

##### <font color='blue'> Solução </font>

<font color='blue'> Tomando $m_{21} = -\frac{a_{21}}{a_{11}} = -2$ e $m_{31} = -\frac{a_{31}}{a_{11}} = -1$ temos:<br><br>
 $$
\left[ \begin{array}{ccc}
	1       & 3    & 2 \\
	2 	    & 1    & -1 \\
	1       & 0    & 1  \\
\end{array}\right]
\begin{array}{c}
	L_{2} \leftrightarrow L_{2} + m_{21}L_{1}   \Rightarrow  \\
	L_{3} \leftrightarrow L_{3} + m_{31}L_{1}   \Rightarrow  \\
\end{array}
\left[ \begin{array}{ccc}
	1       & 3    & 2 \\
	0 	    & -5    & -5 \\
	0       & -3    & -1 \\
\end{array}\right].
$$<br>
 Tomando $m_{23} = -\frac{a_{23}}{a_{22}} = -\frac{3}{5}$, temos:<br><br>
 $$
\left[ \begin{array}{ccc}
	1       & 3     & 2 \\
	0 	    & -5    & -5 \\
	0       & -3     & -1  \\
\end{array}\right]
L_{3} \leftrightarrow L_{3} + m_{32}L_{2}   \Rightarrow  \left[ \begin{array}{ccc}
	1       & 3     & 2 \\
	0 	    & -5    & -5 \\
	0       & 0     & 2  \\
\end{array}\right].
$$<br>
 Portanto,<br><br>
 $$
L = \left[ \begin{array}{ccc}
	1       & 0    & 0 \\
	2 	    & 1    & 0 \\
	1       & \frac{3}{5}    & 1  \\
\end{array}\right]
\, \, \, \, \, \, \, e \, \, \, \, \, \, \,
U = \left[ \begin{array}{ccc}
	1       & 3     & 2 \\
	0 	    & -5    & -5 \\
	0       &0      & 2  \\
\end{array}\right].
$$

# <div style="margin-top: -20px;">
<hr style="border: 2px solid black;">

<font color='black'><span style="font-size: 22px;"><strong>17.2 Resolução de Um Sistema Linear Via Decomposição $LU$</strong></span></font>

<hr style="border: 2px solid black;">
</div>

Considere o sistema $AX = B$ em sua forma matricial, com $det(A) \neq 0$. Suponha que $A$ possa se decompor no produto de uma matriz triangular inferior $L$, e uma matriz triangular superior $U$, tal que $A = LU$. Assim, $AX = B$ equvale a $(LU)X = B$. Dessa forma, obtemos dois sistemas $LY = B$ e $UX = Y$. Como $L$ e $U$ são triangulares temos que a resolução destes sistemas é feita por substituição retroativa.

#### <font color='blue'> Exemplo 2 </font>

<font color='blue'> Aplique o método da decomposição $LU$ ao sistema<br><br>
 $$\left\{ \begin{array}{ccccccc}
2x_{1}  &+& 3x_{2} &-& x_{3}  &=& 5 \\
4x_{1}  &+& 4x_{2} &-& 3x_{3} &=& 3 \\
2x_{1}  &-& 3x_{2} &+& x_{3}  &=& -1\\
\end{array}.\right.
$$

##### <font color='blue'> Solução </font>

<font color='blue'> Nosso ponto de partida é a matriz $A$ do sistema, que é dada por<br><br>
 $$
\left[ \begin{array}{ccc}
2       & 3    & -1 \\
4 	    & 4    & -3 \\
2       &-3    & 1  \\
\end{array}\right]
$$<br>
 Temos que $m_{21} = -\frac{a_{21}}{a_{11}} = -2$ e $m_{31} = -\frac{a_{31}}{a_{11}} = -1$, donde obtemos<br><br>
 $$
\left[ \begin{array}{ccc}
2       & 3    & -1 \\
4 	    & 4    & -3 \\
2       &-3    & 1  \\
\end{array}\right]
\begin{array}{c}
L_{2} \leftrightarrow L_{2} + m_{21}L_{1}   \Rightarrow  \\
L_{3} \leftrightarrow L_{3} + m_{31}L_{1}   \Rightarrow  \\
\end{array}
\left[ \begin{array}{ccc}
2       & 3    & -1 \\
0 	    & -2    & -1 \\
0       &-6    & 2  \\
\end{array}\right].
$$<br>
 Tomando agora $m_{23} = -\frac{a_{23}}{a_{22}}$, temos<br><br>
 $$
\left[ \begin{array}{ccc}
2       & 3    & -1 \\
0 	    & -2    & -1 \\
0       &-6    & 2  \\
\end{array}\right]
L_{3} \leftrightarrow L_{3} + m_{32}L_{2}   \Rightarrow  \\
\left[ \begin{array}{ccc}
2       & 3    & -1 \\
0 	    & -2    & -1 \\
0       &0    & 5  \\
\end{array}\right].
$$<br>
 Portanto,<br><br>
 $$
L = \left[ \begin{array}{ccc}
1       & 0    & 0 \\
2 	    & 1    & 0 \\
1       &3    & 1  \\
\end{array}\right]
\, \, \, \, \, \, \, e \, \, \, \, \, \, \,
U = \left[ \begin{array}{ccc}
2       & 3    & -1 \\
0 	    & -2    & -1 \\
0       &0    & 5  \\
\end{array}\right].
$$<br>
 Assim, o sistema $LY = B$ equivale a:<br><br>
 $$
\left[ \begin{array}{ccc}
 1  & 0 & 0  \\
 2  & 1  & 0  \\
 1 & 3 & 1 \\
\end{array}\right]
\left[ \begin{array}{c}
 y_{1}  \\
 y_{2}  \\
 y_{3} \\
\end{array}\right]
=
\left[ \begin{array}{c}
 5  \\
 3  \\
 -1 \\
\end{array}\right]
\Rightarrow
\left\{ \begin{array}{ccccccc}
  & &  & & y_{1}  &=& 5 \\
  & & 2y_{1} &+& y_{2} &=& 3 \\
y_{1}  &+& 3y_{2} &+& y_{3}  &=& -1\\
\end{array}.\right.
$$<br>
 Por meio de substituição, temos $y_{1} = 5$, $y_{2} = -7$ e $y_{3} = 15$. Agora, podemos montar o sistema $UX = Y$.<br><br>
 $$
\left[ \begin{array}{ccc}
 2  & 3 & -1  \\
 0  & -2  & -1  \\
 0 & 0 & 5 \\
\end{array}\right]
\left[ \begin{array}{c}
 x_{1}  \\
 x_{2}  \\
 x_{3} \\
\end{array}\right]
=
\left[ \begin{array}{c}
 5  \\
 -7  \\
 15 \\
\end{array}\right]
\Rightarrow
\left\{ \begin{array}{ccccccc}
2x_{1}  & +& 3x_{2} & -& x_{3}  &=& 5 \\
  & & 2x_{2} &-& x_{3} &=& -7 \\
  & &   & & 5x_{3}  &=& 15\\
\end{array}.\right.
$$<br>
 Novamente, por substituição, temos $x_{1} = 1$, $x_{2} = 2$ e $x_{3} = 3$.

# <div style="margin-top: -20px;">
<hr style="border: 2px solid black;">

<font color='black'><span style="font-size: 22px;"><strong>17.3 Inversão de Matrizes Usando Decomposição $LU$</strong></span></font>

<hr style="border: 2px solid black;">
</div>

Sabemos que uma matriz $A_{n \times n}$ tal que $det(A) \neq 0$ possui inversa $A^{-1}$. Uma forma de se obter $A^{-1}$ consiste em resolvermos $n$ sistemas lineares. De fato, se quisermos obter a matriz $A^{-1}$, que denotaremos por $X_{A}$, devemos resolver o sistema geral $AX_{A} = I$, em que $I$ é a identidade de ordem $n$. Tal sistema pode ser decomposto em $n$ sistemas independentes:<br><br>
$$AX_{1} = [1, 0, 0, \ldots, 0]^{T}, \, \, AX_{2} = [0, 1, 0, \ldots, 0]^{T}, \ldots, AX_{j} = [0, 0, \ldots, j, \ldots, 0]^{T}, AX_{n}= [0; 0; 0; \ldots; 1]^{T},$$<br>
em que $X_{j}$ é o vetor coluna formado pela $j$-ésima coluna de $X_{A}$, isto é $X_{j} = [x_{1j}, x_{2j}, x_{3j}, \ldots, x_{nj}]^{T}$. Ao final,<br><br>
$$A^{-1} = X_{A} = \left[ \begin{array}{cccccc}
	x_{11} & x_{12} & \ldots & x_{1j} & \ldots & x_{1n} \\
	x_{21} & x_{22} & \ldots & x_{2j} & \ldots &x_{2n} \\
	\vdots & \vdots & \vdots & \vdots & \vdots &\vdots \\
	x_{n1} & x_{n2} & \ldots & x_{nj} & \ldots & x_{nn} \\
\end{array}\right]$$

#### <font color='blue'> Exemplo 3 </font>

<font color='blue'> Encontre a inversa da matriz<br><br>
 $$A = \left[ \begin{array}{ccc}
1 & 3 & 2 \\
2 & 1 & -1 \\
1 & 0 & 1 \\
\end{array}\right].
$$

##### <font color='blue'> Solução </font>

<font color='blue'> Aproveitando a decomposição $LU$ realizada no referido Exemplo, temos, apenas que resolver alguns sistemas lineares por substituição retroativa. Os dois primeiros são $LY = B_{1}$, em que $B_{1} = [1,0,0]^{T}$ e, $UX = Y$. Mais explicitamente,<br>
 $$
\left[ \begin{array}{ccc}
	1  & 0 & 0  \\
	2  & 1  & 0  \\
	1 & \frac{3}{5} & 1 \\
\end{array}\right]
\left[ \begin{array}{c}
	y_{11}  \\
	y_{21}  \\
	y_{31} \\
\end{array}\right]
=
\left[ \begin{array}{c}
	1  \\
	0  \\
	0 \\
\end{array}\right]
\Rightarrow
\left\{ \begin{array}{ccccccc}
	& &  & & y_{11}  &=& 1 \\
	& & 2y_{11} &+& y_{21} &=& 0 \\
	y_{11}  &+& \frac{3}{5}y_{21} &+& y_{31}  &=& 0\\
\end{array}.\right.
$$<br>
 Por meio de substituição, temos $y_{11} = 1$, $y_{21} = -2$ e $y_{31} = \frac{1}{5}$. Agora, podemos montar o sistema $UX = Y$.<br><br>
 $$
\left[ \begin{array}{ccc}
	1  & 3   & 2  \\
	0  & -5  & -5  \\
	0  & 0   & 2 \\
\end{array}\right]
\left[ \begin{array}{c}
	x_{11}  \\
	x_{12}  \\
	x_{13} \\
\end{array}\right]
=
\left[ \begin{array}{c}
	1  \\
	-2  \\
	\frac{1}{5} \\
\end{array}\right]
\Rightarrow
\left\{ \begin{array}{ccccccc}
  x_{11}  & +& 3x_{21} & +& 2x_{31}  &=& 1 \\
	& -& 5x_{21} &-& 5x_{31} &=& -2 \\
	& &   & & 2x_{31}  &=& \frac{1}{5} \\
\end{array}.\right.
$$<br>
 Novamente, aplicando substituição retroativa ao sistema anterior, obtemos: $x_{11} =-\frac{1}{10}, x_{21} = \frac{3}{10}, x_{31} =\frac{1}{10}$.<br><br>
 Analogamente, repassando $B_{1}$ para $B_{2} = [0,1,0]^{T}$, temos:<br><br>
 $$
\left[ \begin{array}{ccc}
	1  & 0 & 0  \\
	2  & 1  & 0  \\
	1 & \frac{3}{5} & 1 \\
\end{array}\right]
\left[ \begin{array}{c}
	y_{21}  \\
	y_{22}  \\
	y_{23} \\
\end{array}\right]
=
\left[ \begin{array}{c}
	0  \\
	1  \\
	0 \\
\end{array}\right]
\Rightarrow \,\,\, [\ldots] \,\,\, \Rightarrow  x_{21} =\frac{3}{10}, x_{22} = \frac{1}{10}, x_{23} =-\frac{3}{10}
$$<br>
 Por fim, para $B_{3} = [0,0,1]^{T}$, temos:<br><br>
 $$
\left[ \begin{array}{ccc}
	1  & 0 & 0  \\
	2  & 1  & 0  \\
	1 & \frac{3}{5} & 1 \\
\end{array}\right]
\left[ \begin{array}{c}
	y_{31}  \\
	y_{32}  \\
	y_{33} \\
\end{array}\right]
=
\left[ \begin{array}{c}
	0  \\
	0  \\
	1 \\
\end{array}\right]
\Rightarrow \,\,\, [\ldots] \,\,\, \Rightarrow  x_{31} =\frac{1}{2}, x_{32} = -\frac{1}{2}, x_{33}= \frac{1}{2}
$$<br>
 Portanto,<br><br>
 $$A^{-1} = 
\left[ \begin{array}{ccc}
	x_{11}  & x_{12}   & x_{13} \\
	x_{21}  & x_{22}   & x_{23} \\
	x_{31}  & x_{32}   & x_{33} \\
\end{array}\right] = 
\left[ \begin{array}{ccc}
	-\frac{1}{10}  & \frac{3}{10}   & \frac{1}{2} \\
	\frac{3}{10}   & \frac{1}{10}   & -\frac{1}{2}  \\
	\frac{1}{10}   & -\frac{3}{10}  & \frac{1}{2} \\
\end{array}\right].$$

# <div style="margin-top: -20px;">
<hr style="border: 2px solid black;">

<font color='black'><span style="font-size: 22px;"><strong>Implementações</strong></span></font>

<hr style="border: 2px solid black;">
</div>

#### <font color='darkblue'> Código Python: Matrizes da Decomposição LU</font>

In [1]:
from numpy import*

def decomposicao_LU(A):
    A = matrix(A, dtype=float)
    n = shape(A)[0]


    U = copy(A)
    n = shape(U)[0]

    L = eye(n)
    for j in arange(n - 1):
        for i in arange(j + 1, n):
            L[i, j] = U[i, j] / U[j, j]
            for k in arange(j + 1, n):
                U[i, k] = U[i, k] - L[i, j] * U[j, k]
            U[i, j] = 0

    print(f'As matrizes L e U associadas à decomposição LU da matriz em questão são dadas por:\n'
          '  Matriz L\n'
          f'{L}\n'
          '  Matriz U\n'
          f'{U}')
    print('')


In [2]:
decomposicao_LU(([[1,3,2],[2,1,-1],[1,0,1]]))

As matrizes L e U associadas à decomposição LU da matriz em questão são dadas por:
  Matriz L
[[1.  0.  0. ]
 [2.  1.  0. ]
 [1.  0.6 1. ]]
  Matriz U
[[ 1.  3.  2.]
 [ 0. -5. -5.]
 [ 0.  0.  2.]]



# <div style="margin-top: -20px;">
<hr style="border: 2px solid black;">

<font color='black'><span style="font-size: 22px;"><strong>Exercícios</strong></span></font>

<hr style="border: 2px solid black;">
</div>

#### Exercício 1

Determine a solução dos seguintes sistemas lineares utilizando decomposição $LU$:

a) 
$
\left\{ \begin{array}{ccccc}
2x_{1}  &+&  5x_{2} &=& 6  \\
x_{1}  &+&  x_{2} &=& \frac{3}{2} \\
\end{array}\right.
\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ $
b)
$
\left\{ \begin{array}{ccccccc}
2x_{1}  &+&  x_{2} &-& x_{3}  &=& -\frac{1}{3}  \\
x_{1}  &+&  x_{2} &+& x_{3}  &=& -\frac{1}{6} \\
3x_{1}  &-& x_{2}  &-& 3x_{3} &=& -\frac{3}{2} \\
\end{array}\right.
$

#### Exercício 2

Encontre a inversa da matriz a seguir usando Decomposição $LU$:

$$
A = \left[ \begin{array}{ccc}
2  & 1 & 1  \\
1  & 1  & 1  \\
2 & 3 & 2 \\
\end{array}\right].
$$

# <div style="margin-top: -20px;">
<hr style="border: 2px solid black;">

<font color='black'><span style="font-size: 22px;"><strong>Respostas dos Exercícios</strong></span></font>

<hr style="border: 2px solid black;">
</div>

#### Resposta do Exercício 1

a) $\left[ \frac{1}{2}, 1 \right]^{T}$; 

b) $\left[ \frac{1}{2}, -1; \frac{1}{3} \right]^{T}$.

#### Resposta do Exercício 2

$
A^{-1} = \left[ \begin{array}{ccc}
1  & -1 & 0  \\
0  & -2  & 1  \\
-1 & 4 & -1 \\
\end{array}\right]. 
$

# <div style="margin-top: -20px;">
<hr style="border: 2px solid black;">

<font color='black'><span style="font-size: 22px;"><strong>Vídeo Aulas</strong></span></font>

<hr style="border: 2px solid black;">
</div>

Clicando nos links a seguir você será redirecionado às aulas referentes a este capítulo:

[Decomposição LU](https://youtu.be/LKgNk1gVcZQ)

[Solução de Um Sistema Linear Via Decomposição LU](https://youtu.be/0Nj2c4bdwPs)

[Inversão de Matrizes Usando Decomposição LU](https://youtu.be/Qe7pVAAsO9g)